name: twitch_dart
description: A twitch API wrapper for Dart. Allow to simply manage multiple twitch clients.
version: 0.0.1
homepage: https://github.com/shalien/twitch_dart

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  dotenv:
dependencies: {http: ^0.13.4}
